# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kevin Lin
email: hello@kevinl.info
description: >-
  CS Educator. Social/Data/Computer Scientist.
logo: "/assets/images/kevin.jpg"
baseurl: ""
url: "https://kevinl.info"
permalink: pretty
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "redirects.json"]

name: Kevin Lin
author: Kevin Lin
author_image: "/assets/images/kevin.jpg"
button_link: "https://calendar.google.com/calendar/selfsched?sstoken=UUowZ0M1TUlSMXFffGRlZmF1bHR8YmI1YmZkNjM2MjJiMDdlMzdmNzI4ZmMyMTExOGY0ZGM&ctz=America/Los_Angeles"
button_text: "Schedule a meeting"

social:
  name: Kevin Lin
  links:
    - https://facebook.com/kevinl.info
    - https://github.com/kevinlin1
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/images/kevin.jpg"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blank_lines: false
  profile: false
