# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kevin Lin
email: hello@kevinl.info
description: >-
  Creating effective, equitable, accessible CS education.
logo: "/assets/images/kevin.jpg"
baseurl: ""
url: "https://kevinl.info"
permalink: /:categories/:title/
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "redirects.json"]
author: Kevin Lin

buttons:
  Schedule a meeting:
    - "/meet/"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
