title: &title Kevin Lin
description: >-
  Creating effective, equitable, accessible CS education.
logo: "/assets/images/kevin.jpg"
baseurl: ""
url: "https://kevinl.info"
permalink: /:categories/:title/
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "redirects.json"]
author: *title

buttons:
  he/him:
    - "https://www.mypronouns.org/he-him"
  Schedule a meeting:
    - "/meet/"

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
