# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kevin Lin
email: hello@kevinl.info
description: >-
  CS Educator. Data Scientist. Software Engineer.
logo: "/assets/images/me.png"
baseurl: ""
url: "https://kevinl.info"
permalink: pretty

name: Kevin Lin
author: Kevin Lin
author_image: "/assets/images/me.png"

social:
  name: Kevin Lin
  links:
    - https://facebook.com/kevinl.info
    - https://github.com/kevinlin1
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/images/me.png"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blank_lines: false
  profile: false
